using System;
using BachelorProjectBackend.Models;
using MySql.Data.MySqlClient;
using MongoDB.Bson;

/// <summary>
/// Produces Persons 
/// </summary>
public static class PersonFactory
{
	public static Person Create(MySqlDataReader row)
    {
        row.Read();

        Person p = new Person()
        {
            PersonId = (int)row[0],
            EmployeeId = (int)row[1],
            Person_Address1 = row[2].ToString(),
            Person_Address2 = row[3].ToString(),
            Person_Address3 = row[4].ToString(),
            Person_Address4 = row[5].ToString(),
            Person_Address5 = row[6].ToString(),
            Person_Name = row[7].ToString(),
            Person_BirthDate = (DateTime)row[8],
            Person_Class = row[9].ToString(),
            Person_Description = row[10].ToString(),
            Person_Gender = row[11].ToString(),
            Person_LastName = row[12].ToString(),
            Person_CountryId = row[13].ToString(),
            Person_FullName = row[14].ToString(),
            Person_Phone = row[15].ToString(),
            Person_FavoritePizza = row[16].ToString(),
            Person_CustomFields = row[17].ToString(),
            DefaultCompanyId = row[18].ToString(),
            Person_FavoritePasta = row[19].ToString(),
            Person_Division = row[20].ToString(),
            Person_Email = row[21].ToString(),
            Person_Rating = row[22].ToString(),
            Person_Reference = row[23].ToString(),
            Person_FirstName2 = row[24].ToString(),
            Person_FaxNumber = row[25].ToString(),
            Person_StoneBricksID = row[26].ToString(),
            Person_Group = row[27].ToString(),
            Person_GroupCode = row[28].ToString(),
            Person_HasData = (Boolean)row[29],
            Person_String = row[30].ToString(),
            Person_FavoriteInstrument = row[31].ToString(),
            MyAccountId1 = row[32].ToString(),
            MyAccountId2 = row[33].ToString(),
            Person_InternalCode = row[34].ToString(),
            Person_HasParty = (Boolean)row[35],
            Person_IsCompany = (Boolean)row[36],
            Person_IsPhilosopher = (Boolean)row[37],
            Person_HasCompany = (Boolean)row[38],   
            Person_IsSupplier = (Boolean)row[39],
            Person_HasIssues = (Boolean)row[40],
            Person_isPerson = (Boolean)row[41],
            Person_IsNaturalPerson = (Boolean)row[42],
            Person_IsProfessional = (Boolean)row[43],
            Person_IsReseller = (Boolean)row[44],
            Person_IsTaxPayer = (Boolean)row[45],
            Person_LastName2 = row[46].ToString(),
            Person_LEIA = row[47].ToString(),
            Person_FavoriteMOvie = row[48].ToString(),
            Person_MiddleNames = row[49].ToString(),
            Person_Migration = row[50].ToString(),
            Person_LaundryRisk = row[51].ToString(),
            Person_PassportNumber = row[52].ToString(),
            Person_PersonalNumber = row[53].ToString(),
            Person_PhoneHome = row[54].ToString(),
            Person_PhoneMobile = row[55].ToString(),
            Person_PhoneWork = row[56].ToString(),
            Person_PostageAddressAttention = row[57].ToString(),
            Person_PostageAddressCity = row[58].ToString(),
            Person_PostageAddressCO = row[59].ToString(),
            PostageAddressCountryId = row[60].ToString(),
            Person_PostageAddressDepartment = row[61].ToString(),
            Person_PostageAddressStreet = row[62].ToString(),
            Person_PostageAddressZip = row[63].ToString(),
            Person_BrokerNode = row[64].ToString(),
            Person_Opinions = row[65].ToString(),
            Person_MovieComment = row[66].ToString(),
            Person_CreditCardCode = row[67].ToString(),
            Person_FavoriteDrink = row[68].ToString(),
            Person_PepsiStatus = (int)row[69],
            Person_PrintStatus = (int)row[70],
            Person_PrintStatusTimeStamp = (DateTime)row[71],
            Person_PrintStatusTimeStampString = row[72].ToString(),
            Person_RatingAgency = row[73].ToString(),
            ResellerId = row[74].ToString(),
            Person_Section = row[75].ToString(),
            Person_Sector = row[76].ToString(),
            Person_Signing = row[77].ToString(),
            Person_Taxi = row[78].ToString(),
            Person_KnowledgeLevel = row[79].ToString(),
            Country2 = row[80].ToString(),
            Person_Id2 = row[81].ToString(),
            Person_IdType = row[82].ToString(),
            Person_ManualHandling = (Boolean)row[83],
            InstanceId = row[84].ToString()
        };
        return p; 
    }

    public static Person Create(BsonDocument row)
    {
        // Removes the _id 
        row.RemoveAt(0);

        Person person = new Person()
        {
            PersonId = Int32.Parse(row.GetElement(0).Value.ToString()),
            EmployeeId = Int32.Parse(row.GetElement(1).Value.ToString()),
            Person_Address1 = row.GetElement(2).Value.ToString(),
            Person_Address2 = row.GetElement(3).Value.ToString(),
            Person_Address3 = row.GetElement(4).Value.ToString(),
            Person_Address4 = row.GetElement(5).Value.ToString(),
            Person_Address5 = row.GetElement(6).Value.ToString(),
            Person_Name = row.GetElement(7).Value.ToString(),
            Person_BirthDate = Convert.ToDateTime(row.GetElement(8).Value.ToString()),
            Person_Class = row.GetElement(9).Value.ToString(),
            Person_Description = row.GetElement(10).Value.ToString(),
            Person_Gender = row.GetElement(11).Value.ToString(),
            Person_LastName = row.GetElement(12).Value.ToString(),
            Person_CountryId = row.GetElement(13).Value.ToString(),
            Person_FullName = row.GetElement(14).Value.ToString(),
            Person_Phone = row.GetElement(15).Value.ToString(),
            Person_FavoritePizza = row.GetElement(16).Value.ToString(),
            Person_CustomFields = row.GetElement(17).Value.ToString(),
            DefaultCompanyId = row.GetElement(18).Value.ToString(),
            Person_FavoritePasta = row.GetElement(19).Value.ToString(),
            Person_Division = row.GetElement(20).Value.ToString(),
            Person_Email = row.GetElement(21).Value.ToString(),
            Person_Rating = row.GetElement(22).Value.ToString(),
            Person_Reference = row.GetElement(23).Value.ToString(),
            Person_FirstName2 = row.GetElement(24).Value.ToString(),
            Person_FaxNumber = row.GetElement(25).Value.ToString(),
            Person_StoneBricksID = row.GetElement(26).Value.ToString(),
            Person_Group = row.GetElement(27).Value.ToString(),
            Person_GroupCode = row.GetElement(28).Value.ToString(),
            Person_HasData = Convert.ToBoolean(row.GetElement(29).Value.ToString()),
            Person_String = row.GetElement(30).Value.ToString(),
            Person_FavoriteInstrument = row.GetElement(31).Value.ToString(),
            MyAccountId1 = row.GetElement(32).Value.ToString(),
            MyAccountId2 = row.GetElement(33).Value.ToString(),
            Person_InternalCode = row.GetElement(34).Value.ToString(),
            Person_HasParty = Convert.ToBoolean(row.GetElement(35).Value.ToString()),
            Person_IsCompany = Convert.ToBoolean(row.GetElement(36).Value.ToString()),
            Person_IsPhilosopher = Convert.ToBoolean(row.GetElement(37).Value.ToString()),
            Person_HasCompany = Convert.ToBoolean(row.GetElement(38).Value.ToString()),
            Person_IsSupplier = Convert.ToBoolean(row.GetElement(39).Value.ToString()),
            Person_HasIssues = Convert.ToBoolean(row.GetElement(40).Value.ToString()),
            Person_isPerson = Convert.ToBoolean(row.GetElement(41).Value.ToString()),
            Person_IsNaturalPerson = Convert.ToBoolean(row.GetElement(42).Value.ToString()),
            Person_IsProfessional = Convert.ToBoolean(row.GetElement(43).Value.ToString()),
            Person_IsReseller = Convert.ToBoolean(row.GetElement(44).Value.ToString()),
            Person_IsTaxPayer = Convert.ToBoolean(row.GetElement(45).Value.ToString()),
            Person_LastName2 = row.GetElement(46).Value.ToString(),
            Person_LEIA = row.GetElement(47).Value.ToString(),
            Person_FavoriteMOvie = row.GetElement(48).Value.ToString(),
            Person_MiddleNames = row.GetElement(49).Value.ToString(),
            Person_Migration = row.GetElement(50).Value.ToString(),
            Person_LaundryRisk = row.GetElement(51).Value.ToString(),
            Person_PassportNumber = row.GetElement(52).Value.ToString(),
            Person_PersonalNumber = row.GetElement(53).Value.ToString(),
            Person_PhoneHome = row.GetElement(54).Value.ToString(),
            Person_PhoneMobile = row.GetElement(55).Value.ToString(),
            Person_PhoneWork = row.GetElement(56).Value.ToString(),
            Person_PostageAddressAttention = row.GetElement(57).Value.ToString(),
            Person_PostageAddressCity = row.GetElement(58).Value.ToString(),
            Person_PostageAddressCO = row.GetElement(59).Value.ToString(),
            PostageAddressCountryId = row.GetElement(60).Value.ToString(),
            Person_PostageAddressDepartment = row.GetElement(61).Value.ToString(),
            Person_PostageAddressStreet = row.GetElement(62).Value.ToString(),
            Person_PostageAddressZip = row.GetElement(63).Value.ToString(),
            Person_BrokerNode = row.GetElement(64).Value.ToString(),
            Person_Opinions = row.GetElement(65).Value.ToString(),
            Person_MovieComment = row.GetElement(66).Value.ToString(),
            Person_CreditCardCode = row.GetElement(67).Value.ToString(),
            Person_FavoriteDrink = row.GetElement(68).Value.ToString(),
            Person_PepsiStatus = Int32.Parse(row.GetElement(69).Value.ToString()),
            Person_PrintStatus = Int32.Parse(row.GetElement(70).Value.ToString()),
            Person_PrintStatusTimeStamp = Convert.ToDateTime(row.GetElement(8).Value.ToString()),
            Person_PrintStatusTimeStampString = row.GetElement(72).Value.ToString(),
            Person_RatingAgency = row.GetElement(73).Value.ToString(),
            ResellerId = row.GetElement(74).Value.ToString(),
            Person_Section = row.GetElement(75).Value.ToString(),
            Person_Sector = row.GetElement(76).Value.ToString(),
            Person_Signing = row.GetElement(77).Value.ToString(),
            Person_Taxi = row.GetElement(78).Value.ToString(),
            Person_KnowledgeLevel = row.GetElement(79).Value.ToString(),
            Country2 = row.GetElement(80).Value.ToString(),
            Person_Id2 = row.GetElement(81).Value.ToString(),
            Person_IdType = row.GetElement(82).Value.ToString(),
            Person_ManualHandling = Convert.ToBoolean(row.GetElement(83).Value.ToString()),
            InstanceId = row.GetElement(84).Value.ToString()
        };
        
        return person;
    }
}
